"""Web UI authentication — mirrors the legacy scheme.

Same design as ``vpngate_manager``: the dashboard is served under a random
``secret_path`` prefix, a password login mints a deterministic session token
(``sha256(username:password:salt)``) delivered as an ``HttpOnly`` cookie, and a
session store tracks expiry. Using the same salt/username means credentials
generated by the legacy install work here too.

``Auth`` is credential-injected so it is fully unit-testable; the CLI builds one
from the legacy config (or a generated fallback) at startup.
"""

from __future__ import annotations

import hashlib
import secrets
import time
from typing import Callable

_SALT = "aimilivpn_secure_salt_2026"     # same as the legacy engine
_COOKIE = "session"
_TTL = 30 * 24 * 3600                     # 30 days, matching legacy Max-Age


def session_token(password: str, username: str = "admin", salt: str = _SALT) -> str:
    return hashlib.sha256(f"{username}:{password}{salt}".encode("utf-8")).hexdigest()


def parse_cookies(cookie_header: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for item in (cookie_header or "").split(";"):
        if "=" in item:
            k, v = item.split("=", 1)
            out[k.strip()] = v.strip()
    return out


class Auth:
    """Password + secret-path + session-cookie gate for the dashboard."""

    def __init__(
        self,
        password: str,
        secret_path: str,
        username: str = "admin",
        ttl: int = _TTL,
        clock: Callable[[], float] = time.time,
    ) -> None:
        self.password = password or ""
        self.secret_path = (secret_path or "").strip("/")
        self.username = username
        self.ttl = ttl
        self._clock = clock
        self._sessions: dict[str, float] = {}

    @property
    def enabled(self) -> bool:
        return bool(self.password)

    @property
    def prefix(self) -> str:
        """URL prefix everything is served under, e.g. ``/EJsW2EeBo9lY``."""
        return f"/{self.secret_path}" if self.secret_path else ""

    def login(self, password: str) -> str | None:
        """Verify password; on success mint+store a token and return it."""
        if not self.enabled:
            return None
        if secrets.compare_digest(password or "", self.password):
            token = session_token(self.password, self.username)
            self._sessions[token] = self._clock() + self.ttl
            return token
        return None

    def valid_token(self, token: str) -> bool:
        exp = self._sessions.get(token or "")
        if exp is None:
            return False
        if exp < self._clock():
            self._sessions.pop(token, None)
            return False
        return True

    def authed(self, cookie_header: str) -> bool:
        if not self.enabled:
            return True
        return self.valid_token(parse_cookies(cookie_header).get(_COOKIE, ""))

    def cookie_header(self, token: str) -> str:
        path = f"{self.prefix}/" if self.prefix else "/"
        return (f"{_COOKIE}={token}; Path={path}; HttpOnly; SameSite=Lax; "
                f"Max-Age={self.ttl}")


def generate_secret_path(n: int = 12) -> str:
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "".join(secrets.choice(alphabet) for _ in range(n))


def generate_password(n: int = 16) -> str:
    return secrets.token_urlsafe(n)
